### ISSUE TITLE
Support lower min SDK than 15

### ISSUE THREAD

**Issue by Maxxan** [NightlyNexus/ViewStatePagerAdapter#14]
For the library the min SDK is 15. Since the page adapter you're using is from the support library, then I think you should be able use a lower the min SDK for the library as well, or it will not be possible to use for projects with min SDK lower than 15.

**Comment by NightlyNexus** [comment]
What version of Android do you need to support?
Version 26.0.0 of the support library only supports 14+. (There happen to be no devices in the wild that run 14, as all updated to 15.)

**Comment by Maxxan** [comment]
I understand and accept your reasoning.. :)
Personally I still need to support APK 10 for half a year more or so, but I could use the overrideLibrary flag, no problem!

**Comment by NightlyNexus** [comment]
Yeah, I'd rather keep up to date with the current version of the support library.
`overrideLibrary` would be a good option. This code is also unlikely to change much, so copying and pasting the one class into your codebase is also a reasonable option.

**Comment by NightlyNexus** [comment]
The support library has minimum of 14. There are no users on 14, so 15 is the real minimum.
No action to take here.
