### ISSUE TITLE
How to get this work with fragments?

### ISSUE THREAD

**Issue by derrysd** [NightlyNexus/ViewStatePagerAdapter#4]

**Comment by NightlyNexus** [comment]
The v4 support library already includes a [FragmentStatePagerAdapter](https://developer.android.com/reference/android/support/v4/app/FragmentStatePagerAdapter.html). Does that do what you want?

**Comment by derrysd** [comment]
oh. sorry for asking such silly question

**Comment by NightlyNexus** [comment]
I'm happy to help! 😃
